# Generated by Django 4.2.1 on 2023-08-17 16:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='farm name', max_length=20, verbose_name='Farm Name')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326, verbose_name='Farm borders as a polygon')),
                ('trees_type', models.CharField(choices=[('ï»¿Apples', 'Apples'), ('Oranges', 'Oranges'), ('Mangoes', 'Mangoes'), ('Lemons', 'Lemons'), ('Pears', 'Pears'), ('Apricots', 'Apricots'), ('Coconuts', 'Coconuts'), ('Plum', 'Plum'), ('Almond', 'Almond'), ('Indian Gooseberry', 'Indian Gooseberry'), ('Cherry', 'Cherry'), ('Mulberry', 'Mulberry'), ('Peach', 'Peach'), ('Fig', 'Fig'), ('Persimmon', 'Persimmon'), ('Pomegranate', 'Pomegranate'), ('Grapefruit', 'Grapefruit'), ('Avocado', 'Avocado'), ('Jaboticaba fruit', 'Jaboticaba fruit'), ('Lemon', 'Lemon'), ('Lime', 'Lime'), ('Guava', 'Guava'), ('Olive', 'Olive'), ('Lychee', 'Lychee'), ('Durian', 'Durian'), ('Jackfruit', 'Jackfruit'), ('Cashew', 'Cashew'), ('Abiu', 'Abiu'), ('Bael', 'Bael'), ('Ber', 'Ber'), ('Carambola', 'Carambola'), ('Crab Apple', 'Crab Apple'), ('Elderberry', 'Elderberry'), ('Kumquat', 'Kumquat'), ('Loquat', 'Loquat'), ('Papaya', 'Papaya'), ('Pecan', 'Pecan'), ('Pomelo', 'Pomelo'), ('Quince', 'Quince'), ('Rambutan', 'Rambutan'), ('Sapodilla', 'Sapodilla'), ('Soursop', 'Soursop'), ('Sweet Chestnut', 'Sweet Chestnut'), ('Tamarillo', 'Tamarillo'), ('Jamaican Tangelo', 'Jamaican Tangelo'), ('Walnut', 'Walnut')], max_length=20, verbose_name='Farm trees type')),
                ('date', models.DateField(verbose_name='Farm Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius', models.FloatField(default=1)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
        ),
    ]
